attach volume

diff --git a/rootfs/opt/qserv/bin/qserv-compute-volId b/rootfs/opt/qserv/bin/qserv-compute-volId
--- a/rootfs/opt/qserv/bin/qserv-compute-volId
+++ b/rootfs/opt/qserv/bin/qserv-compute-volId
@@ -8,6 +8,20 @@ Usage:`basename $0`
     -p volume prefix
 EOD
 }
+# Check if openstack connection parameters are available
+OS_RC_FILE="$CLUSTER_CONFIG_DIR/os-openrc.sh"
+if [ -z "$OS_PROJECT_NAME" ]; then
+    if [ -f "$OS_RC_FILE" ]; then
+        . "$OS_RC_FILE"
+    else
+        echo "ERROR: Missing Openstack resource file: $OS_RC_FILE"
+        exit 1
+    fi
+    if [ -z "$OS_PROJECT_NAME" ]; then
+        echo "ERROR: Incorrect Openstack resource file: $OS_RC_FILE"
+        exit 1
+    fi
+fi
 
 while getopts ":t:p:" c; do
     case $c in
@@ -32,4 +46,5 @@ volume_list=`openstack volume list -c ID -c Name -f csv | grep ${p} | awk -F\, '
 volume_list=`echo ${volume_list} | sed -e 's/\"\ \"/\",\"/g' | sed -e "s/\${p}//g" | sed -e 's/;/=/g'`
 volume_list={${volume_list}}
 
-echo $volume_list >> volume_list
+echo "firstVolume="$t >> /qserv-deploy/config/volume_list
+echo "volumeId="$volume_list >> /qserv-deploy/config/volume_list
